name: Deploy API and UI to Azure Web Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-api:
    name: Deploy API to Azure Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_API_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: ./api

  deploy-ui:
    name: Deploy UI to Azure Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy UI folder (Streamlit) to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_UI_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_UI_PUBLISH_PROFILE }}
          package: ./ui  # 👈 Not zipped!
